# AuthorAI - the Streamlit web page.
import streamlit as st
from readability import analyze_text
from ai_service import get_tough_sentences, generate_blog, AIUnavailable
import demo_data

MIN_WORDS = 30      # shorter text = not meaningful
MAX_WORDS = 8000    # larger text = too big

st.set_page_config(page_title="AuthorAI", page_icon="✍️", layout="wide")

# ---------- Styling ----------
st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;800&display=swap');
html, body, [class*="css"] { font-family: 'Inter', sans-serif; }
.stApp { background: #ffffff; }
.hero { text-align:center; padding: 28px 0 12px; }
.hero h1 { font-size: 3rem; font-weight: 800; color:#4f46e5; margin:0; }
.hero p { color:#64748b; font-size:1.15rem; margin-top:4px; }
.card { background:#f8fafc; border:1px solid #e2e8f0; border-radius:14px;
        padding:18px; text-align:center; }
.card .label { color:#64748b; font-size:.85rem; text-transform:uppercase; letter-spacing:.05em; }
.card .value { color:#0f172a; font-size:2rem; font-weight:800; }
.bar { background:#e2e8f0; border-radius:99px; height:14px; overflow:hidden; margin-top:8px; }
.bar > div { height:100%; border-radius:99px; }
.badge { display:inline-block; color:white; padding:4px 14px; border-radius:99px; font-weight:600; }
div.stButton > button { border-radius:10px; font-weight:600; padding:.6rem 1.4rem; }
</style>
""", unsafe_allow_html=True)

st.markdown('<div class="hero"><h1>✍️ AuthorAI</h1>'
            '<p>Smart Readability &amp; Content Assistant</p></div>', unsafe_allow_html=True)


def stat_card(label, value):
    st.markdown(f'<div class="card"><div class="label">{label}</div>'
                f'<div class="value">{value}</div></div>', unsafe_allow_html=True)


def demo_notice(extra):
    st.warning("AI service is temporarily unavailable. Demo mode is being used.")
    st.info(f"🧪 **Demo / Fallback Mode** – {extra} This was NOT generated by the live AI.")


# ---------- Input ----------
if st.button("Use sample chapter"):
    st.session_state["chapter"] = demo_data.DEMO_CHAPTER

text = st.text_area("Chapter", key="chapter", height=260,
                    placeholder="Paste your chapter or content here...",
                    label_visibility="collapsed")

if st.button("Analyze Chapter", type="primary"):
    word_count = len(text.split())
    if not text.strip():
        st.warning("Please paste a chapter before analyzing.")
    elif word_count < MIN_WORDS:
        st.warning("Please enter a longer piece of text for meaningful readability analysis.")
    elif word_count > MAX_WORDS:
        st.warning(f"Text is too large. Please paste less than {MAX_WORDS} words at a time.")
    else:
        with st.spinner("Analyzing your chapter..."):
            stats = analyze_text(text)
            try:
                sentences, mode = get_tough_sentences(text), "live"
            except AIUnavailable:
                sentences, mode = demo_data.DEMO_SENTENCES, "demo"
        st.session_state["result"] = {"text": text, "stats": stats,
                                      "sentences": sentences, "mode": mode, "blog": None}

# ---------- Results ----------
result = st.session_state.get("result")
if result:
    s = result["stats"]

    st.subheader("📊 Readability Analysis")
    c1, c2, c3, c4 = st.columns(4)
    with c1: stat_card("Total Words", s["words"])
    with c2: stat_card("Total Sentences", s["sentences"])
    with c3: stat_card("Avg Sentence Length", s["avg_length"])
    with c4: stat_card("Readability Score", s["score"])

    score_width = max(0, min(100, s["score"]))
    st.markdown(
        f'<div class="card" style="margin-top:14px;text-align:left">'
        f'<b>Reading difficulty:</b> <span class="badge" style="background:{s["color"]}">{s["level"]}</span>'
        f'<div class="bar"><div style="width:{score_width}%;background:{s["color"]}"></div></div>'
        f'<small style="color:#64748b">Higher score = easier to read (0–100)</small></div>',
        unsafe_allow_html=True)

    st.subheader("🔍 Top 5 Toughest Sentences")
    if result["mode"] == "demo":
        demo_notice("These are sample results for a built-in sample chapter, not your text.")
    else:
        st.caption("✅ Generated live by Gemini AI")
    for i, item in enumerate(result["sentences"], 1):
        with st.container(border=True):
            st.markdown(f"**{i}. Original Sentence**")
            st.write(item["original"])
            st.markdown("**Why is it difficult?**")
            st.write(item["why"])
            st.markdown("**Simpler Version**")
            st.success(item["simpler"])

    st.subheader("📝 150-Word Blog")
    if st.button("Generate 150-Word Blog"):
        with st.spinner("Writing your blog..."):
            try:
                result["blog"], result["blog_mode"] = generate_blog(result["text"]), "live"
            except AIUnavailable:
                result["blog"], result["blog_mode"] = demo_data.DEMO_BLOG, "demo"

    if result["blog"]:
        if result["blog_mode"] == "demo":
            demo_notice("This blog is a sample about the built-in sample chapter.")
        else:
            st.caption("✅ Generated live by Gemini AI")
        st.code(result["blog"], language=None, wrap_lines=True)  # copy icon at top-right
        st.caption(f"{len(result['blog'].split())} words · Click the copy icon above to copy.")

st.divider()
st.caption("AI content is meant to make readers curious. It does not guarantee any number of readers.")
